### ISSUE TITLE
While asking for graph, plot is displaying and hold still we close the window

### ISSUE THREAD

**Issue by vpurandara** [Sinaptik-AI/pandas-ai#520] opened 2023-09-01 18:39 UTC
### 🐛 Describe the bug
@gventuri 

```
llm = OpenAI(api_token=OpenAI_ACCESSKEY)
pandas_ai = PandasAI(llm, conversational=True, save_charts=True, enable_cache=True, save_charts_path=user_defined_path, middlewares= [ChartsMiddleware()])
```
I tried both ways for saving a chart
1.
```
 analytics_df = SmartDataframe(
             analytics_df,
             config={
               "llm": llm,
                 "save_charts_path": user_defined_path,
                "save_charts": True,
                 "verbose": True,
                "middlewares" : []
            }
        )
   response = analytics_df.chat(
            "pie graph On Leads Assigned To,"
            "with filename as tmp123.png "
        )
```

2.
```
response = pandas_ai(analytics_df, prompt=f"{inputQuestion}, as png image with filename as exports/charts/{timestamp}2.png ") 
```

Both the ways are perfectly saving the graphs but also ploting the graphs , whhere manually need to close the window to complete the execution

code generated in logs
```
2023-09-02 00:05:15 [WARNING] Error of executing code
2023-09-02 00:05:43 [INFO] Question: pie graph On Leads Assigned To,with filename as tmp123.png 
2023-09-02 00:05:43 [INFO] Running PandasAI with openai LLM...
2023-09-02 00:05:43 [INFO] Prompt ID: 91fd2612-2fed-48ca-9d87-e6ba3b2ae21f
2023-09-02 00:05:55 [INFO] 
                    Code generated:
                    '''
                    # TODO import all the dependencies required
import pandas as pd
import matplotlib.pyplot as plt

# Analyze the data
# 1. Prepare: Preprocessing and cleaning data if necessary
# 2. Process: Manipulating data for analysis (grouping, filtering, aggregating, etc.)
# 3. Analyze: Conducting the actual analysis (if the user asks to create a chart save it to an image in exports/charts/temp_chart.png and do not show the chart.)
# 4. Output: return a dictionary of:
# - type (possible values "text", "number", "dataframe", "plot")
# - value (can be a string, a dataframe or the path of the plot, NOT a dictionary)
# Example output: { "type": "text", "value": "The average loan amount is $15,000." }
def analyze_data(dfs: list[pd.DataFrame]) -> dict:
    # Code goes here (do not add comments)
    df = dfs[0]
    leads_assigned_to = df['Assigned To'].value_counts()
    
    # Create a pie chart
    plt.figure(figsize=(8, 6))
    plt.pie(leads_assigned_to, labels=leads_assigned_to.index, autopct='%1.1f%%')
    plt.title('Leads Assigned To')
    
    # Save the chart to a file
    filename = 'tmp123.png'
    plt.savefig(f'exports/charts/{filename}')
    plt.close()
    
    return {"type": "plot", "value": f'exports/charts/{filename}'}

# Declare a result variable
result = analyze_data(dfs)
                    '''
                
2023-09-02 00:05:55 [INFO] 
Code running:
'''
def analyze_data(dfs: list[pd.DataFrame]) ->dict:
    df = dfs[0]
    leads_assigned_to = df['Assigned To'].value_counts()
    plt.figure(figsize=(8, 6))
    plt.pie(leads_assigned_to, labels=leads_assigned_to.index, autopct='%1.1f%%')
    plt.title('Leads Assigned To')
    filename = 'tmp123.png'
    plt.savefig(f'exports/charts/{filename}')
    plt.close()
    return {'type': 'plot', 'value': f'exports/charts/{filename}'}


result = analyze_data(dfs)
        '''
2023-09-02 00:05:56 [INFO] Answer: {'type': 'plot', 'value': 'exports/charts/tmp123.png'}
2023-09-02 00:05:56 [INFO] Executed in: 13.013440608978271s
```

**Comment by anauwal** [comment] 2023-09-18 05:51
please fix this @gventuri

**Comment by anauwal** [comment] 2023-09-18 10:03
please urgently fix it because i must close the plot every time! @gventuri

**Comment by gventuri** [comment] 2023-09-18 14:50
@anauwal this is not actually a bug, but rather how matplotlib works. We can find some workarounds for that, but it really depends on your expected behavior. For example, when you ask to plot a chat, what do you expect to happen? Let me know so that I can figure out how to make it work for you :)

**Comment by anauwal** [comment] 2023-09-24 09:29
well, i want it to save the plot in the background, i want to make an web based api in this, please how to fix it @gventuri

**Comment by gventuri** [comment] 2023-09-24 12:56
@anauwal what happens if you try with  saving the plots to a custom path? https://docs.pandas-ai.com/en/latest/examples/#saving-plots-with-user-defined-path

**Comment by anauwal** [comment] 2023-09-24 13:01
the image is saved but the plot window is showing too, i have to close it everytime i execute a plot

**Comment by gventuri** [comment] 2023-09-25 21:56
@anauwal try updating to the latest version and passing `open_charts`: False in the config

**Closed** 2024-03-03 18:16 UTC
